name: Blushing Mulberry
favicon: null
layout_spectrum: 0.7422274360433221
typography_spectrum: 0.23873072094283998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f4ec'
    - '#cecabe'
    - '#0d0805'
    - '#6d5b4e'
    - '#c9a279'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
