name: Blushing Mulberry
favicon: null
layout_spectrum: 0.7422274360433221
typography_spectrum: 0.23873072094283998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3935046554543078
  lightness: 0.7562347108032554
  saturation: 0.8555623630527407
  rhythmicContrast: 0.9602978129405528
purpose: []
